group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
unstable_features = true
style_edition = "2024"
edition = "2024"
reorder_impl_items = true
format_code_in_doc_comments = true
